	nios_system u0 (
		.b_emp_export            (<connected-to-b_emp_export>),            //            b_emp.export
		.bullet1_en_export       (<connected-to-bullet1_en_export>),       //       bullet1_en.export
		.bullet1_x_export        (<connected-to-bullet1_x_export>),        //        bullet1_x.export
		.bullet1_y_export        (<connected-to-bullet1_y_export>),        //        bullet1_y.export
		.bullet2_en_export       (<connected-to-bullet2_en_export>),       //       bullet2_en.export
		.bullet2_x_export        (<connected-to-bullet2_x_export>),        //        bullet2_x.export
		.bullet2_y_export        (<connected-to-bullet2_y_export>),        //        bullet2_y.export
		.bullet3_en_export       (<connected-to-bullet3_en_export>),       //       bullet3_en.export
		.bullet3_x_export        (<connected-to-bullet3_x_export>),        //        bullet3_x.export
		.bullet3_y_export        (<connected-to-bullet3_y_export>),        //        bullet3_y.export
		.clk_clk                 (<connected-to-clk_clk>),                 //              clk.clk
		.explosion1_en_export    (<connected-to-explosion1_en_export>),    //    explosion1_en.export
		.explosion1_x_export     (<connected-to-explosion1_x_export>),     //     explosion1_x.export
		.explosion1_y_export     (<connected-to-explosion1_y_export>),     //     explosion1_y.export
		.explosion2_en_export    (<connected-to-explosion2_en_export>),    //    explosion2_en.export
		.explosion2_x_export     (<connected-to-explosion2_x_export>),     //     explosion2_x.export
		.explosion2_y_export     (<connected-to-explosion2_y_export>),     //     explosion2_y.export
		.explosion3_en_export    (<connected-to-explosion3_en_export>),    //    explosion3_en.export
		.explosion3_x_export     (<connected-to-explosion3_x_export>),     //     explosion3_x.export
		.explosion3_y_export     (<connected-to-explosion3_y_export>),     //     explosion3_y.export
		.health_export           (<connected-to-health_export>),           //           health.export
		.key_export              (<connected-to-key_export>),              //              key.export
		.keycode_export          (<connected-to-keycode_export>),          //          keycode.export
		.kraid_as_dir_export     (<connected-to-kraid_as_dir_export>),     //     kraid_as_dir.export
		.kraid_dir_export        (<connected-to-kraid_dir_export>),        //        kraid_dir.export
		.kraid_g_en_export       (<connected-to-kraid_g_en_export>),       //       kraid_g_en.export
		.kraid_n_en_export       (<connected-to-kraid_n_en_export>),       //       kraid_n_en.export
		.kraid_r_en_export       (<connected-to-kraid_r_en_export>),       //       kraid_r_en.export
		.kraid_shoot_en_export   (<connected-to-kraid_shoot_en_export>),   //   kraid_shoot_en.export
		.kraid_spike_x_export    (<connected-to-kraid_spike_x_export>),    //    kraid_spike_x.export
		.kraid_spike_y_export    (<connected-to-kraid_spike_y_export>),    //    kraid_spike_y.export
		.kraid_throw_en_export   (<connected-to-kraid_throw_en_export>),   //   kraid_throw_en.export
		.kraid_throw_x_export    (<connected-to-kraid_throw_x_export>),    //    kraid_throw_x.export
		.kraid_throw_y_export    (<connected-to-kraid_throw_y_export>),    //    kraid_throw_y.export
		.kraid_x_export          (<connected-to-kraid_x_export>),          //          kraid_x.export
		.kraid_y_export          (<connected-to-kraid_y_export>),          //          kraid_y.export
		.loss_en_export          (<connected-to-loss_en_export>),          //          loss_en.export
		.monster1_en_export      (<connected-to-monster1_en_export>),      //      monster1_en.export
		.monster1_x_export       (<connected-to-monster1_x_export>),       //       monster1_x.export
		.monster1_y_export       (<connected-to-monster1_y_export>),       //       monster1_y.export
		.monster2_en_export      (<connected-to-monster2_en_export>),      //      monster2_en.export
		.monster2_x_export       (<connected-to-monster2_x_export>),       //       monster2_x.export
		.monster2_y_export       (<connected-to-monster2_y_export>),       //       monster2_y.export
		.monster3_dir_export     (<connected-to-monster3_dir_export>),     //     monster3_dir.export
		.monster3_en_export      (<connected-to-monster3_en_export>),      //      monster3_en.export
		.monster3_x_export       (<connected-to-monster3_x_export>),       //       monster3_x.export
		.monster3_y_export       (<connected-to-monster3_y_export>),       //       monster3_y.export
		.otg_hpi_address_export  (<connected-to-otg_hpi_address_export>),  //  otg_hpi_address.export
		.otg_hpi_cs_export       (<connected-to-otg_hpi_cs_export>),       //       otg_hpi_cs.export
		.otg_hpi_data_in_port    (<connected-to-otg_hpi_data_in_port>),    //     otg_hpi_data.in_port
		.otg_hpi_data_out_port   (<connected-to-otg_hpi_data_out_port>),   //                 .out_port
		.otg_hpi_r_export        (<connected-to-otg_hpi_r_export>),        //        otg_hpi_r.export
		.otg_hpi_w_export        (<connected-to-otg_hpi_w_export>),        //        otg_hpi_w.export
		.reset_reset_n           (<connected-to-reset_reset_n>),           //            reset.reset_n
		.samus_dir_export        (<connected-to-samus_dir_export>),        //        samus_dir.export
		.samus_en_export         (<connected-to-samus_en_export>),         //         samus_en.export
		.samus_jump_export       (<connected-to-samus_jump_export>),       //       samus_jump.export
		.samus_up_export         (<connected-to-samus_up_export>),         //         samus_up.export
		.samus_walk_export       (<connected-to-samus_walk_export>),       //       samus_walk.export
		.samus_x_export          (<connected-to-samus_x_export>),          //          samus_x.export
		.samus_y_export          (<connected-to-samus_y_export>),          //          samus_y.export
		.scene_sel_export        (<connected-to-scene_sel_export>),        //        scene_sel.export
		.sdram_clk_clk           (<connected-to-sdram_clk_clk>),           //        sdram_clk.clk
		.sdram_wire_addr         (<connected-to-sdram_wire_addr>),         //       sdram_wire.addr
		.sdram_wire_ba           (<connected-to-sdram_wire_ba>),           //                 .ba
		.sdram_wire_cas_n        (<connected-to-sdram_wire_cas_n>),        //                 .cas_n
		.sdram_wire_cke          (<connected-to-sdram_wire_cke>),          //                 .cke
		.sdram_wire_cs_n         (<connected-to-sdram_wire_cs_n>),         //                 .cs_n
		.sdram_wire_dq           (<connected-to-sdram_wire_dq>),           //                 .dq
		.sdram_wire_dqm          (<connected-to-sdram_wire_dqm>),          //                 .dqm
		.sdram_wire_ras_n        (<connected-to-sdram_wire_ras_n>),        //                 .ras_n
		.sdram_wire_we_n         (<connected-to-sdram_wire_we_n>),         //                 .we_n
		.title_en_export         (<connected-to-title_en_export>),         //         title_en.export
		.win_en_export           (<connected-to-win_en_export>),           //           win_en.export
		.krait_throw_2_en_export (<connected-to-krait_throw_2_en_export>), // krait_throw_2_en.export
		.krait_throw_2_x_export  (<connected-to-krait_throw_2_x_export>),  //  krait_throw_2_x.export
		.krait_throw_2_y_export  (<connected-to-krait_throw_2_y_export>)   //  krait_throw_2_y.export
	);

