/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_qsys_0' in SOPC Builder design 'nios_system'
 * SOPC Builder design path: ../../nios_system.sopcinfo
 *
 * Generated: Mon Dec 05 16:41:47 CST 2016
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00001020
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1d
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x10000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1d
#define ALT_CPU_NAME "nios2_qsys_0"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x10000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00001020
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1d
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x10000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1d
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x10000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_NIOS2_GEN2
#define __ALTPLL


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x440
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x440
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x440
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios_system"


/*
 * b_emp configuration
 *
 */

#define ALT_MODULE_CLASS_b_emp altera_avalon_pio
#define B_EMP_BASE 0x130
#define B_EMP_BIT_CLEARING_EDGE_REGISTER 0
#define B_EMP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_EMP_CAPTURE 0
#define B_EMP_DATA_WIDTH 1
#define B_EMP_DO_TEST_BENCH_WIRING 0
#define B_EMP_DRIVEN_SIM_VALUE 0
#define B_EMP_EDGE_TYPE "NONE"
#define B_EMP_FREQ 50000000
#define B_EMP_HAS_IN 0
#define B_EMP_HAS_OUT 1
#define B_EMP_HAS_TRI 0
#define B_EMP_IRQ -1
#define B_EMP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define B_EMP_IRQ_TYPE "NONE"
#define B_EMP_NAME "/dev/b_emp"
#define B_EMP_RESET_VALUE 0
#define B_EMP_SPAN 16
#define B_EMP_TYPE "altera_avalon_pio"


/*
 * bullet1_en configuration
 *
 */

#define ALT_MODULE_CLASS_bullet1_en altera_avalon_pio
#define BULLET1_EN_BASE 0x230
#define BULLET1_EN_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET1_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET1_EN_CAPTURE 0
#define BULLET1_EN_DATA_WIDTH 1
#define BULLET1_EN_DO_TEST_BENCH_WIRING 0
#define BULLET1_EN_DRIVEN_SIM_VALUE 0
#define BULLET1_EN_EDGE_TYPE "NONE"
#define BULLET1_EN_FREQ 50000000
#define BULLET1_EN_HAS_IN 0
#define BULLET1_EN_HAS_OUT 1
#define BULLET1_EN_HAS_TRI 0
#define BULLET1_EN_IRQ -1
#define BULLET1_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET1_EN_IRQ_TYPE "NONE"
#define BULLET1_EN_NAME "/dev/bullet1_en"
#define BULLET1_EN_RESET_VALUE 0
#define BULLET1_EN_SPAN 16
#define BULLET1_EN_TYPE "altera_avalon_pio"


/*
 * bullet1_x configuration
 *
 */

#define ALT_MODULE_CLASS_bullet1_x altera_avalon_pio
#define BULLET1_X_BASE 0x220
#define BULLET1_X_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET1_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET1_X_CAPTURE 0
#define BULLET1_X_DATA_WIDTH 10
#define BULLET1_X_DO_TEST_BENCH_WIRING 0
#define BULLET1_X_DRIVEN_SIM_VALUE 0
#define BULLET1_X_EDGE_TYPE "NONE"
#define BULLET1_X_FREQ 50000000
#define BULLET1_X_HAS_IN 0
#define BULLET1_X_HAS_OUT 1
#define BULLET1_X_HAS_TRI 0
#define BULLET1_X_IRQ -1
#define BULLET1_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET1_X_IRQ_TYPE "NONE"
#define BULLET1_X_NAME "/dev/bullet1_x"
#define BULLET1_X_RESET_VALUE 0
#define BULLET1_X_SPAN 16
#define BULLET1_X_TYPE "altera_avalon_pio"


/*
 * bullet1_y configuration
 *
 */

#define ALT_MODULE_CLASS_bullet1_y altera_avalon_pio
#define BULLET1_Y_BASE 0x210
#define BULLET1_Y_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET1_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET1_Y_CAPTURE 0
#define BULLET1_Y_DATA_WIDTH 10
#define BULLET1_Y_DO_TEST_BENCH_WIRING 0
#define BULLET1_Y_DRIVEN_SIM_VALUE 0
#define BULLET1_Y_EDGE_TYPE "NONE"
#define BULLET1_Y_FREQ 50000000
#define BULLET1_Y_HAS_IN 0
#define BULLET1_Y_HAS_OUT 1
#define BULLET1_Y_HAS_TRI 0
#define BULLET1_Y_IRQ -1
#define BULLET1_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET1_Y_IRQ_TYPE "NONE"
#define BULLET1_Y_NAME "/dev/bullet1_y"
#define BULLET1_Y_RESET_VALUE 0
#define BULLET1_Y_SPAN 16
#define BULLET1_Y_TYPE "altera_avalon_pio"


/*
 * bullet2_en configuration
 *
 */

#define ALT_MODULE_CLASS_bullet2_en altera_avalon_pio
#define BULLET2_EN_BASE 0x200
#define BULLET2_EN_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET2_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET2_EN_CAPTURE 0
#define BULLET2_EN_DATA_WIDTH 1
#define BULLET2_EN_DO_TEST_BENCH_WIRING 0
#define BULLET2_EN_DRIVEN_SIM_VALUE 0
#define BULLET2_EN_EDGE_TYPE "NONE"
#define BULLET2_EN_FREQ 50000000
#define BULLET2_EN_HAS_IN 0
#define BULLET2_EN_HAS_OUT 1
#define BULLET2_EN_HAS_TRI 0
#define BULLET2_EN_IRQ -1
#define BULLET2_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET2_EN_IRQ_TYPE "NONE"
#define BULLET2_EN_NAME "/dev/bullet2_en"
#define BULLET2_EN_RESET_VALUE 0
#define BULLET2_EN_SPAN 16
#define BULLET2_EN_TYPE "altera_avalon_pio"


/*
 * bullet2_x configuration
 *
 */

#define ALT_MODULE_CLASS_bullet2_x altera_avalon_pio
#define BULLET2_X_BASE 0x1f0
#define BULLET2_X_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET2_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET2_X_CAPTURE 0
#define BULLET2_X_DATA_WIDTH 10
#define BULLET2_X_DO_TEST_BENCH_WIRING 0
#define BULLET2_X_DRIVEN_SIM_VALUE 0
#define BULLET2_X_EDGE_TYPE "NONE"
#define BULLET2_X_FREQ 50000000
#define BULLET2_X_HAS_IN 0
#define BULLET2_X_HAS_OUT 1
#define BULLET2_X_HAS_TRI 0
#define BULLET2_X_IRQ -1
#define BULLET2_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET2_X_IRQ_TYPE "NONE"
#define BULLET2_X_NAME "/dev/bullet2_x"
#define BULLET2_X_RESET_VALUE 0
#define BULLET2_X_SPAN 16
#define BULLET2_X_TYPE "altera_avalon_pio"


/*
 * bullet2_y configuration
 *
 */

#define ALT_MODULE_CLASS_bullet2_y altera_avalon_pio
#define BULLET2_Y_BASE 0x1e0
#define BULLET2_Y_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET2_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET2_Y_CAPTURE 0
#define BULLET2_Y_DATA_WIDTH 10
#define BULLET2_Y_DO_TEST_BENCH_WIRING 0
#define BULLET2_Y_DRIVEN_SIM_VALUE 0
#define BULLET2_Y_EDGE_TYPE "NONE"
#define BULLET2_Y_FREQ 50000000
#define BULLET2_Y_HAS_IN 0
#define BULLET2_Y_HAS_OUT 1
#define BULLET2_Y_HAS_TRI 0
#define BULLET2_Y_IRQ -1
#define BULLET2_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET2_Y_IRQ_TYPE "NONE"
#define BULLET2_Y_NAME "/dev/bullet2_y"
#define BULLET2_Y_RESET_VALUE 0
#define BULLET2_Y_SPAN 16
#define BULLET2_Y_TYPE "altera_avalon_pio"


/*
 * bullet3_en configuration
 *
 */

#define ALT_MODULE_CLASS_bullet3_en altera_avalon_pio
#define BULLET3_EN_BASE 0x1d0
#define BULLET3_EN_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET3_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET3_EN_CAPTURE 0
#define BULLET3_EN_DATA_WIDTH 1
#define BULLET3_EN_DO_TEST_BENCH_WIRING 0
#define BULLET3_EN_DRIVEN_SIM_VALUE 0
#define BULLET3_EN_EDGE_TYPE "NONE"
#define BULLET3_EN_FREQ 50000000
#define BULLET3_EN_HAS_IN 0
#define BULLET3_EN_HAS_OUT 1
#define BULLET3_EN_HAS_TRI 0
#define BULLET3_EN_IRQ -1
#define BULLET3_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET3_EN_IRQ_TYPE "NONE"
#define BULLET3_EN_NAME "/dev/bullet3_en"
#define BULLET3_EN_RESET_VALUE 0
#define BULLET3_EN_SPAN 16
#define BULLET3_EN_TYPE "altera_avalon_pio"


/*
 * bullet3_x configuration
 *
 */

#define ALT_MODULE_CLASS_bullet3_x altera_avalon_pio
#define BULLET3_X_BASE 0x1c0
#define BULLET3_X_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET3_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET3_X_CAPTURE 0
#define BULLET3_X_DATA_WIDTH 10
#define BULLET3_X_DO_TEST_BENCH_WIRING 0
#define BULLET3_X_DRIVEN_SIM_VALUE 0
#define BULLET3_X_EDGE_TYPE "NONE"
#define BULLET3_X_FREQ 50000000
#define BULLET3_X_HAS_IN 0
#define BULLET3_X_HAS_OUT 1
#define BULLET3_X_HAS_TRI 0
#define BULLET3_X_IRQ -1
#define BULLET3_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET3_X_IRQ_TYPE "NONE"
#define BULLET3_X_NAME "/dev/bullet3_x"
#define BULLET3_X_RESET_VALUE 0
#define BULLET3_X_SPAN 16
#define BULLET3_X_TYPE "altera_avalon_pio"


/*
 * bullet3_y configuration
 *
 */

#define ALT_MODULE_CLASS_bullet3_y altera_avalon_pio
#define BULLET3_Y_BASE 0x1b0
#define BULLET3_Y_BIT_CLEARING_EDGE_REGISTER 0
#define BULLET3_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BULLET3_Y_CAPTURE 0
#define BULLET3_Y_DATA_WIDTH 10
#define BULLET3_Y_DO_TEST_BENCH_WIRING 0
#define BULLET3_Y_DRIVEN_SIM_VALUE 0
#define BULLET3_Y_EDGE_TYPE "NONE"
#define BULLET3_Y_FREQ 50000000
#define BULLET3_Y_HAS_IN 0
#define BULLET3_Y_HAS_OUT 1
#define BULLET3_Y_HAS_TRI 0
#define BULLET3_Y_IRQ -1
#define BULLET3_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BULLET3_Y_IRQ_TYPE "NONE"
#define BULLET3_Y_NAME "/dev/bullet3_y"
#define BULLET3_Y_RESET_VALUE 0
#define BULLET3_Y_SPAN 16
#define BULLET3_Y_TYPE "altera_avalon_pio"


/*
 * explosion1_en configuration
 *
 */

#define ALT_MODULE_CLASS_explosion1_en altera_avalon_pio
#define EXPLOSION1_EN_BASE 0x2c0
#define EXPLOSION1_EN_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION1_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION1_EN_CAPTURE 0
#define EXPLOSION1_EN_DATA_WIDTH 1
#define EXPLOSION1_EN_DO_TEST_BENCH_WIRING 0
#define EXPLOSION1_EN_DRIVEN_SIM_VALUE 0
#define EXPLOSION1_EN_EDGE_TYPE "NONE"
#define EXPLOSION1_EN_FREQ 50000000
#define EXPLOSION1_EN_HAS_IN 0
#define EXPLOSION1_EN_HAS_OUT 1
#define EXPLOSION1_EN_HAS_TRI 0
#define EXPLOSION1_EN_IRQ -1
#define EXPLOSION1_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION1_EN_IRQ_TYPE "NONE"
#define EXPLOSION1_EN_NAME "/dev/explosion1_en"
#define EXPLOSION1_EN_RESET_VALUE 0
#define EXPLOSION1_EN_SPAN 16
#define EXPLOSION1_EN_TYPE "altera_avalon_pio"


/*
 * explosion1_x configuration
 *
 */

#define ALT_MODULE_CLASS_explosion1_x altera_avalon_pio
#define EXPLOSION1_X_BASE 0x2b0
#define EXPLOSION1_X_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION1_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION1_X_CAPTURE 0
#define EXPLOSION1_X_DATA_WIDTH 10
#define EXPLOSION1_X_DO_TEST_BENCH_WIRING 0
#define EXPLOSION1_X_DRIVEN_SIM_VALUE 0
#define EXPLOSION1_X_EDGE_TYPE "NONE"
#define EXPLOSION1_X_FREQ 50000000
#define EXPLOSION1_X_HAS_IN 0
#define EXPLOSION1_X_HAS_OUT 1
#define EXPLOSION1_X_HAS_TRI 0
#define EXPLOSION1_X_IRQ -1
#define EXPLOSION1_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION1_X_IRQ_TYPE "NONE"
#define EXPLOSION1_X_NAME "/dev/explosion1_x"
#define EXPLOSION1_X_RESET_VALUE 0
#define EXPLOSION1_X_SPAN 16
#define EXPLOSION1_X_TYPE "altera_avalon_pio"


/*
 * explosion1_y configuration
 *
 */

#define ALT_MODULE_CLASS_explosion1_y altera_avalon_pio
#define EXPLOSION1_Y_BASE 0x2a0
#define EXPLOSION1_Y_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION1_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION1_Y_CAPTURE 0
#define EXPLOSION1_Y_DATA_WIDTH 10
#define EXPLOSION1_Y_DO_TEST_BENCH_WIRING 0
#define EXPLOSION1_Y_DRIVEN_SIM_VALUE 0
#define EXPLOSION1_Y_EDGE_TYPE "NONE"
#define EXPLOSION1_Y_FREQ 50000000
#define EXPLOSION1_Y_HAS_IN 0
#define EXPLOSION1_Y_HAS_OUT 1
#define EXPLOSION1_Y_HAS_TRI 0
#define EXPLOSION1_Y_IRQ -1
#define EXPLOSION1_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION1_Y_IRQ_TYPE "NONE"
#define EXPLOSION1_Y_NAME "/dev/explosion1_y"
#define EXPLOSION1_Y_RESET_VALUE 0
#define EXPLOSION1_Y_SPAN 16
#define EXPLOSION1_Y_TYPE "altera_avalon_pio"


/*
 * explosion2_en configuration
 *
 */

#define ALT_MODULE_CLASS_explosion2_en altera_avalon_pio
#define EXPLOSION2_EN_BASE 0x290
#define EXPLOSION2_EN_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION2_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION2_EN_CAPTURE 0
#define EXPLOSION2_EN_DATA_WIDTH 1
#define EXPLOSION2_EN_DO_TEST_BENCH_WIRING 0
#define EXPLOSION2_EN_DRIVEN_SIM_VALUE 0
#define EXPLOSION2_EN_EDGE_TYPE "NONE"
#define EXPLOSION2_EN_FREQ 50000000
#define EXPLOSION2_EN_HAS_IN 0
#define EXPLOSION2_EN_HAS_OUT 1
#define EXPLOSION2_EN_HAS_TRI 0
#define EXPLOSION2_EN_IRQ -1
#define EXPLOSION2_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION2_EN_IRQ_TYPE "NONE"
#define EXPLOSION2_EN_NAME "/dev/explosion2_en"
#define EXPLOSION2_EN_RESET_VALUE 0
#define EXPLOSION2_EN_SPAN 16
#define EXPLOSION2_EN_TYPE "altera_avalon_pio"


/*
 * explosion2_x configuration
 *
 */

#define ALT_MODULE_CLASS_explosion2_x altera_avalon_pio
#define EXPLOSION2_X_BASE 0x280
#define EXPLOSION2_X_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION2_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION2_X_CAPTURE 0
#define EXPLOSION2_X_DATA_WIDTH 10
#define EXPLOSION2_X_DO_TEST_BENCH_WIRING 0
#define EXPLOSION2_X_DRIVEN_SIM_VALUE 0
#define EXPLOSION2_X_EDGE_TYPE "NONE"
#define EXPLOSION2_X_FREQ 50000000
#define EXPLOSION2_X_HAS_IN 0
#define EXPLOSION2_X_HAS_OUT 1
#define EXPLOSION2_X_HAS_TRI 0
#define EXPLOSION2_X_IRQ -1
#define EXPLOSION2_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION2_X_IRQ_TYPE "NONE"
#define EXPLOSION2_X_NAME "/dev/explosion2_x"
#define EXPLOSION2_X_RESET_VALUE 0
#define EXPLOSION2_X_SPAN 16
#define EXPLOSION2_X_TYPE "altera_avalon_pio"


/*
 * explosion2_y configuration
 *
 */

#define ALT_MODULE_CLASS_explosion2_y altera_avalon_pio
#define EXPLOSION2_Y_BASE 0x270
#define EXPLOSION2_Y_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION2_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION2_Y_CAPTURE 0
#define EXPLOSION2_Y_DATA_WIDTH 10
#define EXPLOSION2_Y_DO_TEST_BENCH_WIRING 0
#define EXPLOSION2_Y_DRIVEN_SIM_VALUE 0
#define EXPLOSION2_Y_EDGE_TYPE "NONE"
#define EXPLOSION2_Y_FREQ 50000000
#define EXPLOSION2_Y_HAS_IN 0
#define EXPLOSION2_Y_HAS_OUT 1
#define EXPLOSION2_Y_HAS_TRI 0
#define EXPLOSION2_Y_IRQ -1
#define EXPLOSION2_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION2_Y_IRQ_TYPE "NONE"
#define EXPLOSION2_Y_NAME "/dev/explosion2_y"
#define EXPLOSION2_Y_RESET_VALUE 0
#define EXPLOSION2_Y_SPAN 16
#define EXPLOSION2_Y_TYPE "altera_avalon_pio"


/*
 * explosion3_en configuration
 *
 */

#define ALT_MODULE_CLASS_explosion3_en altera_avalon_pio
#define EXPLOSION3_EN_BASE 0x260
#define EXPLOSION3_EN_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION3_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION3_EN_CAPTURE 0
#define EXPLOSION3_EN_DATA_WIDTH 1
#define EXPLOSION3_EN_DO_TEST_BENCH_WIRING 0
#define EXPLOSION3_EN_DRIVEN_SIM_VALUE 0
#define EXPLOSION3_EN_EDGE_TYPE "NONE"
#define EXPLOSION3_EN_FREQ 50000000
#define EXPLOSION3_EN_HAS_IN 0
#define EXPLOSION3_EN_HAS_OUT 1
#define EXPLOSION3_EN_HAS_TRI 0
#define EXPLOSION3_EN_IRQ -1
#define EXPLOSION3_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION3_EN_IRQ_TYPE "NONE"
#define EXPLOSION3_EN_NAME "/dev/explosion3_en"
#define EXPLOSION3_EN_RESET_VALUE 0
#define EXPLOSION3_EN_SPAN 16
#define EXPLOSION3_EN_TYPE "altera_avalon_pio"


/*
 * explosion3_x configuration
 *
 */

#define ALT_MODULE_CLASS_explosion3_x altera_avalon_pio
#define EXPLOSION3_X_BASE 0x250
#define EXPLOSION3_X_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION3_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION3_X_CAPTURE 0
#define EXPLOSION3_X_DATA_WIDTH 10
#define EXPLOSION3_X_DO_TEST_BENCH_WIRING 0
#define EXPLOSION3_X_DRIVEN_SIM_VALUE 0
#define EXPLOSION3_X_EDGE_TYPE "NONE"
#define EXPLOSION3_X_FREQ 50000000
#define EXPLOSION3_X_HAS_IN 0
#define EXPLOSION3_X_HAS_OUT 1
#define EXPLOSION3_X_HAS_TRI 0
#define EXPLOSION3_X_IRQ -1
#define EXPLOSION3_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION3_X_IRQ_TYPE "NONE"
#define EXPLOSION3_X_NAME "/dev/explosion3_x"
#define EXPLOSION3_X_RESET_VALUE 0
#define EXPLOSION3_X_SPAN 16
#define EXPLOSION3_X_TYPE "altera_avalon_pio"


/*
 * explosion3_y configuration
 *
 */

#define ALT_MODULE_CLASS_explosion3_y altera_avalon_pio
#define EXPLOSION3_Y_BASE 0x240
#define EXPLOSION3_Y_BIT_CLEARING_EDGE_REGISTER 0
#define EXPLOSION3_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPLOSION3_Y_CAPTURE 0
#define EXPLOSION3_Y_DATA_WIDTH 10
#define EXPLOSION3_Y_DO_TEST_BENCH_WIRING 0
#define EXPLOSION3_Y_DRIVEN_SIM_VALUE 0
#define EXPLOSION3_Y_EDGE_TYPE "NONE"
#define EXPLOSION3_Y_FREQ 50000000
#define EXPLOSION3_Y_HAS_IN 0
#define EXPLOSION3_Y_HAS_OUT 1
#define EXPLOSION3_Y_HAS_TRI 0
#define EXPLOSION3_Y_IRQ -1
#define EXPLOSION3_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXPLOSION3_Y_IRQ_TYPE "NONE"
#define EXPLOSION3_Y_NAME "/dev/explosion3_y"
#define EXPLOSION3_Y_RESET_VALUE 0
#define EXPLOSION3_Y_SPAN 16
#define EXPLOSION3_Y_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * health configuration
 *
 */

#define ALT_MODULE_CLASS_health altera_avalon_pio
#define HEALTH_BASE 0x1a0
#define HEALTH_BIT_CLEARING_EDGE_REGISTER 0
#define HEALTH_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEALTH_CAPTURE 0
#define HEALTH_DATA_WIDTH 2
#define HEALTH_DO_TEST_BENCH_WIRING 0
#define HEALTH_DRIVEN_SIM_VALUE 0
#define HEALTH_EDGE_TYPE "NONE"
#define HEALTH_FREQ 50000000
#define HEALTH_HAS_IN 0
#define HEALTH_HAS_OUT 1
#define HEALTH_HAS_TRI 0
#define HEALTH_IRQ -1
#define HEALTH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEALTH_IRQ_TYPE "NONE"
#define HEALTH_NAME "/dev/health"
#define HEALTH_RESET_VALUE 0
#define HEALTH_SPAN 16
#define HEALTH_TYPE "altera_avalon_pio"


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x440
#define JTAG_UART_0_IRQ 5
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * key configuration
 *
 */

#define ALT_MODULE_CLASS_key altera_avalon_pio
#define KEY_BASE 0x3b0
#define KEY_BIT_CLEARING_EDGE_REGISTER 0
#define KEY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY_CAPTURE 1
#define KEY_DATA_WIDTH 2
#define KEY_DO_TEST_BENCH_WIRING 0
#define KEY_DRIVEN_SIM_VALUE 0
#define KEY_EDGE_TYPE "RISING"
#define KEY_FREQ 50000000
#define KEY_HAS_IN 1
#define KEY_HAS_OUT 0
#define KEY_HAS_TRI 0
#define KEY_IRQ -1
#define KEY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEY_IRQ_TYPE "NONE"
#define KEY_NAME "/dev/key"
#define KEY_RESET_VALUE 0
#define KEY_SPAN 16
#define KEY_TYPE "altera_avalon_pio"


/*
 * keycode configuration
 *
 */

#define ALT_MODULE_CLASS_keycode altera_avalon_pio
#define KEYCODE_BASE 0x3c0
#define KEYCODE_BIT_CLEARING_EDGE_REGISTER 0
#define KEYCODE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYCODE_CAPTURE 0
#define KEYCODE_DATA_WIDTH 16
#define KEYCODE_DO_TEST_BENCH_WIRING 0
#define KEYCODE_DRIVEN_SIM_VALUE 0
#define KEYCODE_EDGE_TYPE "NONE"
#define KEYCODE_FREQ 50000000
#define KEYCODE_HAS_IN 0
#define KEYCODE_HAS_OUT 1
#define KEYCODE_HAS_TRI 0
#define KEYCODE_IRQ -1
#define KEYCODE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE_IRQ_TYPE "NONE"
#define KEYCODE_NAME "/dev/keycode"
#define KEYCODE_RESET_VALUE 0
#define KEYCODE_SPAN 16
#define KEYCODE_TYPE "altera_avalon_pio"


/*
 * kraid_as_dir configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_as_dir altera_avalon_pio
#define KRAID_AS_DIR_BASE 0xb0
#define KRAID_AS_DIR_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_AS_DIR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_AS_DIR_CAPTURE 0
#define KRAID_AS_DIR_DATA_WIDTH 1
#define KRAID_AS_DIR_DO_TEST_BENCH_WIRING 0
#define KRAID_AS_DIR_DRIVEN_SIM_VALUE 0
#define KRAID_AS_DIR_EDGE_TYPE "NONE"
#define KRAID_AS_DIR_FREQ 50000000
#define KRAID_AS_DIR_HAS_IN 0
#define KRAID_AS_DIR_HAS_OUT 1
#define KRAID_AS_DIR_HAS_TRI 0
#define KRAID_AS_DIR_IRQ -1
#define KRAID_AS_DIR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_AS_DIR_IRQ_TYPE "NONE"
#define KRAID_AS_DIR_NAME "/dev/kraid_as_dir"
#define KRAID_AS_DIR_RESET_VALUE 0
#define KRAID_AS_DIR_SPAN 16
#define KRAID_AS_DIR_TYPE "altera_avalon_pio"


/*
 * kraid_dir configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_dir altera_avalon_pio
#define KRAID_DIR_BASE 0x110
#define KRAID_DIR_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_DIR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_DIR_CAPTURE 0
#define KRAID_DIR_DATA_WIDTH 1
#define KRAID_DIR_DO_TEST_BENCH_WIRING 0
#define KRAID_DIR_DRIVEN_SIM_VALUE 0
#define KRAID_DIR_EDGE_TYPE "NONE"
#define KRAID_DIR_FREQ 50000000
#define KRAID_DIR_HAS_IN 0
#define KRAID_DIR_HAS_OUT 1
#define KRAID_DIR_HAS_TRI 0
#define KRAID_DIR_IRQ -1
#define KRAID_DIR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_DIR_IRQ_TYPE "NONE"
#define KRAID_DIR_NAME "/dev/kraid_dir"
#define KRAID_DIR_RESET_VALUE 0
#define KRAID_DIR_SPAN 16
#define KRAID_DIR_TYPE "altera_avalon_pio"


/*
 * kraid_g_en configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_g_en altera_avalon_pio
#define KRAID_G_EN_BASE 0x100
#define KRAID_G_EN_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_G_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_G_EN_CAPTURE 0
#define KRAID_G_EN_DATA_WIDTH 1
#define KRAID_G_EN_DO_TEST_BENCH_WIRING 0
#define KRAID_G_EN_DRIVEN_SIM_VALUE 0
#define KRAID_G_EN_EDGE_TYPE "NONE"
#define KRAID_G_EN_FREQ 50000000
#define KRAID_G_EN_HAS_IN 0
#define KRAID_G_EN_HAS_OUT 1
#define KRAID_G_EN_HAS_TRI 0
#define KRAID_G_EN_IRQ -1
#define KRAID_G_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_G_EN_IRQ_TYPE "NONE"
#define KRAID_G_EN_NAME "/dev/kraid_g_en"
#define KRAID_G_EN_RESET_VALUE 0
#define KRAID_G_EN_SPAN 16
#define KRAID_G_EN_TYPE "altera_avalon_pio"


/*
 * kraid_n_en configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_n_en altera_avalon_pio
#define KRAID_N_EN_BASE 0xe0
#define KRAID_N_EN_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_N_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_N_EN_CAPTURE 0
#define KRAID_N_EN_DATA_WIDTH 1
#define KRAID_N_EN_DO_TEST_BENCH_WIRING 0
#define KRAID_N_EN_DRIVEN_SIM_VALUE 0
#define KRAID_N_EN_EDGE_TYPE "NONE"
#define KRAID_N_EN_FREQ 50000000
#define KRAID_N_EN_HAS_IN 0
#define KRAID_N_EN_HAS_OUT 1
#define KRAID_N_EN_HAS_TRI 0
#define KRAID_N_EN_IRQ -1
#define KRAID_N_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_N_EN_IRQ_TYPE "NONE"
#define KRAID_N_EN_NAME "/dev/kraid_n_en"
#define KRAID_N_EN_RESET_VALUE 0
#define KRAID_N_EN_SPAN 16
#define KRAID_N_EN_TYPE "altera_avalon_pio"


/*
 * kraid_r_en configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_r_en altera_avalon_pio
#define KRAID_R_EN_BASE 0xf0
#define KRAID_R_EN_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_R_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_R_EN_CAPTURE 0
#define KRAID_R_EN_DATA_WIDTH 1
#define KRAID_R_EN_DO_TEST_BENCH_WIRING 0
#define KRAID_R_EN_DRIVEN_SIM_VALUE 0
#define KRAID_R_EN_EDGE_TYPE "NONE"
#define KRAID_R_EN_FREQ 50000000
#define KRAID_R_EN_HAS_IN 0
#define KRAID_R_EN_HAS_OUT 1
#define KRAID_R_EN_HAS_TRI 0
#define KRAID_R_EN_IRQ -1
#define KRAID_R_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_R_EN_IRQ_TYPE "NONE"
#define KRAID_R_EN_NAME "/dev/kraid_r_en"
#define KRAID_R_EN_RESET_VALUE 0
#define KRAID_R_EN_SPAN 16
#define KRAID_R_EN_TYPE "altera_avalon_pio"


/*
 * kraid_shoot_en configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_shoot_en altera_avalon_pio
#define KRAID_SHOOT_EN_BASE 0xd0
#define KRAID_SHOOT_EN_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_SHOOT_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_SHOOT_EN_CAPTURE 0
#define KRAID_SHOOT_EN_DATA_WIDTH 1
#define KRAID_SHOOT_EN_DO_TEST_BENCH_WIRING 0
#define KRAID_SHOOT_EN_DRIVEN_SIM_VALUE 0
#define KRAID_SHOOT_EN_EDGE_TYPE "NONE"
#define KRAID_SHOOT_EN_FREQ 50000000
#define KRAID_SHOOT_EN_HAS_IN 0
#define KRAID_SHOOT_EN_HAS_OUT 1
#define KRAID_SHOOT_EN_HAS_TRI 0
#define KRAID_SHOOT_EN_IRQ -1
#define KRAID_SHOOT_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_SHOOT_EN_IRQ_TYPE "NONE"
#define KRAID_SHOOT_EN_NAME "/dev/kraid_shoot_en"
#define KRAID_SHOOT_EN_RESET_VALUE 0
#define KRAID_SHOOT_EN_SPAN 16
#define KRAID_SHOOT_EN_TYPE "altera_avalon_pio"


/*
 * kraid_spike_x configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_spike_x altera_avalon_pio
#define KRAID_SPIKE_X_BASE 0x80
#define KRAID_SPIKE_X_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_SPIKE_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_SPIKE_X_CAPTURE 0
#define KRAID_SPIKE_X_DATA_WIDTH 10
#define KRAID_SPIKE_X_DO_TEST_BENCH_WIRING 0
#define KRAID_SPIKE_X_DRIVEN_SIM_VALUE 0
#define KRAID_SPIKE_X_EDGE_TYPE "NONE"
#define KRAID_SPIKE_X_FREQ 50000000
#define KRAID_SPIKE_X_HAS_IN 0
#define KRAID_SPIKE_X_HAS_OUT 1
#define KRAID_SPIKE_X_HAS_TRI 0
#define KRAID_SPIKE_X_IRQ -1
#define KRAID_SPIKE_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_SPIKE_X_IRQ_TYPE "NONE"
#define KRAID_SPIKE_X_NAME "/dev/kraid_spike_x"
#define KRAID_SPIKE_X_RESET_VALUE 0
#define KRAID_SPIKE_X_SPAN 16
#define KRAID_SPIKE_X_TYPE "altera_avalon_pio"


/*
 * kraid_spike_y configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_spike_y altera_avalon_pio
#define KRAID_SPIKE_Y_BASE 0x70
#define KRAID_SPIKE_Y_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_SPIKE_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_SPIKE_Y_CAPTURE 0
#define KRAID_SPIKE_Y_DATA_WIDTH 10
#define KRAID_SPIKE_Y_DO_TEST_BENCH_WIRING 0
#define KRAID_SPIKE_Y_DRIVEN_SIM_VALUE 0
#define KRAID_SPIKE_Y_EDGE_TYPE "NONE"
#define KRAID_SPIKE_Y_FREQ 50000000
#define KRAID_SPIKE_Y_HAS_IN 0
#define KRAID_SPIKE_Y_HAS_OUT 1
#define KRAID_SPIKE_Y_HAS_TRI 0
#define KRAID_SPIKE_Y_IRQ -1
#define KRAID_SPIKE_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_SPIKE_Y_IRQ_TYPE "NONE"
#define KRAID_SPIKE_Y_NAME "/dev/kraid_spike_y"
#define KRAID_SPIKE_Y_RESET_VALUE 0
#define KRAID_SPIKE_Y_SPAN 16
#define KRAID_SPIKE_Y_TYPE "altera_avalon_pio"


/*
 * kraid_throw_en configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_throw_en altera_avalon_pio
#define KRAID_THROW_EN_BASE 0xc0
#define KRAID_THROW_EN_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_THROW_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_THROW_EN_CAPTURE 0
#define KRAID_THROW_EN_DATA_WIDTH 1
#define KRAID_THROW_EN_DO_TEST_BENCH_WIRING 0
#define KRAID_THROW_EN_DRIVEN_SIM_VALUE 0
#define KRAID_THROW_EN_EDGE_TYPE "NONE"
#define KRAID_THROW_EN_FREQ 50000000
#define KRAID_THROW_EN_HAS_IN 0
#define KRAID_THROW_EN_HAS_OUT 1
#define KRAID_THROW_EN_HAS_TRI 0
#define KRAID_THROW_EN_IRQ -1
#define KRAID_THROW_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_THROW_EN_IRQ_TYPE "NONE"
#define KRAID_THROW_EN_NAME "/dev/kraid_throw_en"
#define KRAID_THROW_EN_RESET_VALUE 0
#define KRAID_THROW_EN_SPAN 16
#define KRAID_THROW_EN_TYPE "altera_avalon_pio"


/*
 * kraid_throw_x configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_throw_x altera_avalon_pio
#define KRAID_THROW_X_BASE 0x60
#define KRAID_THROW_X_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_THROW_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_THROW_X_CAPTURE 0
#define KRAID_THROW_X_DATA_WIDTH 10
#define KRAID_THROW_X_DO_TEST_BENCH_WIRING 0
#define KRAID_THROW_X_DRIVEN_SIM_VALUE 0
#define KRAID_THROW_X_EDGE_TYPE "NONE"
#define KRAID_THROW_X_FREQ 50000000
#define KRAID_THROW_X_HAS_IN 0
#define KRAID_THROW_X_HAS_OUT 1
#define KRAID_THROW_X_HAS_TRI 0
#define KRAID_THROW_X_IRQ -1
#define KRAID_THROW_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_THROW_X_IRQ_TYPE "NONE"
#define KRAID_THROW_X_NAME "/dev/kraid_throw_x"
#define KRAID_THROW_X_RESET_VALUE 0
#define KRAID_THROW_X_SPAN 16
#define KRAID_THROW_X_TYPE "altera_avalon_pio"


/*
 * kraid_throw_y configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_throw_y altera_avalon_pio
#define KRAID_THROW_Y_BASE 0x50
#define KRAID_THROW_Y_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_THROW_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_THROW_Y_CAPTURE 0
#define KRAID_THROW_Y_DATA_WIDTH 10
#define KRAID_THROW_Y_DO_TEST_BENCH_WIRING 0
#define KRAID_THROW_Y_DRIVEN_SIM_VALUE 0
#define KRAID_THROW_Y_EDGE_TYPE "NONE"
#define KRAID_THROW_Y_FREQ 50000000
#define KRAID_THROW_Y_HAS_IN 0
#define KRAID_THROW_Y_HAS_OUT 1
#define KRAID_THROW_Y_HAS_TRI 0
#define KRAID_THROW_Y_IRQ -1
#define KRAID_THROW_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_THROW_Y_IRQ_TYPE "NONE"
#define KRAID_THROW_Y_NAME "/dev/kraid_throw_y"
#define KRAID_THROW_Y_RESET_VALUE 0
#define KRAID_THROW_Y_SPAN 16
#define KRAID_THROW_Y_TYPE "altera_avalon_pio"


/*
 * kraid_x configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_x altera_avalon_pio
#define KRAID_X_BASE 0xa0
#define KRAID_X_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_X_CAPTURE 0
#define KRAID_X_DATA_WIDTH 10
#define KRAID_X_DO_TEST_BENCH_WIRING 0
#define KRAID_X_DRIVEN_SIM_VALUE 0
#define KRAID_X_EDGE_TYPE "NONE"
#define KRAID_X_FREQ 50000000
#define KRAID_X_HAS_IN 0
#define KRAID_X_HAS_OUT 1
#define KRAID_X_HAS_TRI 0
#define KRAID_X_IRQ -1
#define KRAID_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_X_IRQ_TYPE "NONE"
#define KRAID_X_NAME "/dev/kraid_x"
#define KRAID_X_RESET_VALUE 0
#define KRAID_X_SPAN 16
#define KRAID_X_TYPE "altera_avalon_pio"


/*
 * kraid_y configuration
 *
 */

#define ALT_MODULE_CLASS_kraid_y altera_avalon_pio
#define KRAID_Y_BASE 0x90
#define KRAID_Y_BIT_CLEARING_EDGE_REGISTER 0
#define KRAID_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAID_Y_CAPTURE 0
#define KRAID_Y_DATA_WIDTH 10
#define KRAID_Y_DO_TEST_BENCH_WIRING 0
#define KRAID_Y_DRIVEN_SIM_VALUE 0
#define KRAID_Y_EDGE_TYPE "NONE"
#define KRAID_Y_FREQ 50000000
#define KRAID_Y_HAS_IN 0
#define KRAID_Y_HAS_OUT 1
#define KRAID_Y_HAS_TRI 0
#define KRAID_Y_IRQ -1
#define KRAID_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAID_Y_IRQ_TYPE "NONE"
#define KRAID_Y_NAME "/dev/kraid_y"
#define KRAID_Y_RESET_VALUE 0
#define KRAID_Y_SPAN 16
#define KRAID_Y_TYPE "altera_avalon_pio"


/*
 * krait_throw_2_en configuration
 *
 */

#define ALT_MODULE_CLASS_krait_throw_2_en altera_avalon_pio
#define KRAIT_THROW_2_EN_BASE 0x40
#define KRAIT_THROW_2_EN_BIT_CLEARING_EDGE_REGISTER 0
#define KRAIT_THROW_2_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAIT_THROW_2_EN_CAPTURE 0
#define KRAIT_THROW_2_EN_DATA_WIDTH 1
#define KRAIT_THROW_2_EN_DO_TEST_BENCH_WIRING 0
#define KRAIT_THROW_2_EN_DRIVEN_SIM_VALUE 0
#define KRAIT_THROW_2_EN_EDGE_TYPE "NONE"
#define KRAIT_THROW_2_EN_FREQ 50000000
#define KRAIT_THROW_2_EN_HAS_IN 0
#define KRAIT_THROW_2_EN_HAS_OUT 1
#define KRAIT_THROW_2_EN_HAS_TRI 0
#define KRAIT_THROW_2_EN_IRQ -1
#define KRAIT_THROW_2_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAIT_THROW_2_EN_IRQ_TYPE "NONE"
#define KRAIT_THROW_2_EN_NAME "/dev/krait_throw_2_en"
#define KRAIT_THROW_2_EN_RESET_VALUE 0
#define KRAIT_THROW_2_EN_SPAN 16
#define KRAIT_THROW_2_EN_TYPE "altera_avalon_pio"


/*
 * krait_throw_2_x configuration
 *
 */

#define ALT_MODULE_CLASS_krait_throw_2_x altera_avalon_pio
#define KRAIT_THROW_2_X_BASE 0x30
#define KRAIT_THROW_2_X_BIT_CLEARING_EDGE_REGISTER 0
#define KRAIT_THROW_2_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAIT_THROW_2_X_CAPTURE 0
#define KRAIT_THROW_2_X_DATA_WIDTH 10
#define KRAIT_THROW_2_X_DO_TEST_BENCH_WIRING 0
#define KRAIT_THROW_2_X_DRIVEN_SIM_VALUE 0
#define KRAIT_THROW_2_X_EDGE_TYPE "NONE"
#define KRAIT_THROW_2_X_FREQ 50000000
#define KRAIT_THROW_2_X_HAS_IN 0
#define KRAIT_THROW_2_X_HAS_OUT 1
#define KRAIT_THROW_2_X_HAS_TRI 0
#define KRAIT_THROW_2_X_IRQ -1
#define KRAIT_THROW_2_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAIT_THROW_2_X_IRQ_TYPE "NONE"
#define KRAIT_THROW_2_X_NAME "/dev/krait_throw_2_x"
#define KRAIT_THROW_2_X_RESET_VALUE 0
#define KRAIT_THROW_2_X_SPAN 16
#define KRAIT_THROW_2_X_TYPE "altera_avalon_pio"


/*
 * krait_throw_2_y configuration
 *
 */

#define ALT_MODULE_CLASS_krait_throw_2_y altera_avalon_pio
#define KRAIT_THROW_2_Y_BASE 0x20
#define KRAIT_THROW_2_Y_BIT_CLEARING_EDGE_REGISTER 0
#define KRAIT_THROW_2_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KRAIT_THROW_2_Y_CAPTURE 0
#define KRAIT_THROW_2_Y_DATA_WIDTH 10
#define KRAIT_THROW_2_Y_DO_TEST_BENCH_WIRING 0
#define KRAIT_THROW_2_Y_DRIVEN_SIM_VALUE 0
#define KRAIT_THROW_2_Y_EDGE_TYPE "NONE"
#define KRAIT_THROW_2_Y_FREQ 50000000
#define KRAIT_THROW_2_Y_HAS_IN 0
#define KRAIT_THROW_2_Y_HAS_OUT 1
#define KRAIT_THROW_2_Y_HAS_TRI 0
#define KRAIT_THROW_2_Y_IRQ -1
#define KRAIT_THROW_2_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KRAIT_THROW_2_Y_IRQ_TYPE "NONE"
#define KRAIT_THROW_2_Y_NAME "/dev/krait_throw_2_y"
#define KRAIT_THROW_2_Y_RESET_VALUE 0
#define KRAIT_THROW_2_Y_SPAN 16
#define KRAIT_THROW_2_Y_TYPE "altera_avalon_pio"


/*
 * loss_en configuration
 *
 */

#define ALT_MODULE_CLASS_loss_en altera_avalon_pio
#define LOSS_EN_BASE 0x180
#define LOSS_EN_BIT_CLEARING_EDGE_REGISTER 0
#define LOSS_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LOSS_EN_CAPTURE 0
#define LOSS_EN_DATA_WIDTH 1
#define LOSS_EN_DO_TEST_BENCH_WIRING 0
#define LOSS_EN_DRIVEN_SIM_VALUE 0
#define LOSS_EN_EDGE_TYPE "NONE"
#define LOSS_EN_FREQ 50000000
#define LOSS_EN_HAS_IN 0
#define LOSS_EN_HAS_OUT 1
#define LOSS_EN_HAS_TRI 0
#define LOSS_EN_IRQ -1
#define LOSS_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOSS_EN_IRQ_TYPE "NONE"
#define LOSS_EN_NAME "/dev/loss_en"
#define LOSS_EN_RESET_VALUE 0
#define LOSS_EN_SPAN 16
#define LOSS_EN_TYPE "altera_avalon_pio"


/*
 * monster1_en configuration
 *
 */

#define ALT_MODULE_CLASS_monster1_en altera_avalon_pio
#define MONSTER1_EN_BASE 0x350
#define MONSTER1_EN_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER1_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER1_EN_CAPTURE 0
#define MONSTER1_EN_DATA_WIDTH 1
#define MONSTER1_EN_DO_TEST_BENCH_WIRING 0
#define MONSTER1_EN_DRIVEN_SIM_VALUE 0
#define MONSTER1_EN_EDGE_TYPE "NONE"
#define MONSTER1_EN_FREQ 50000000
#define MONSTER1_EN_HAS_IN 0
#define MONSTER1_EN_HAS_OUT 1
#define MONSTER1_EN_HAS_TRI 0
#define MONSTER1_EN_IRQ -1
#define MONSTER1_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER1_EN_IRQ_TYPE "NONE"
#define MONSTER1_EN_NAME "/dev/monster1_en"
#define MONSTER1_EN_RESET_VALUE 0
#define MONSTER1_EN_SPAN 16
#define MONSTER1_EN_TYPE "altera_avalon_pio"


/*
 * monster1_x configuration
 *
 */

#define ALT_MODULE_CLASS_monster1_x altera_avalon_pio
#define MONSTER1_X_BASE 0x340
#define MONSTER1_X_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER1_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER1_X_CAPTURE 0
#define MONSTER1_X_DATA_WIDTH 10
#define MONSTER1_X_DO_TEST_BENCH_WIRING 0
#define MONSTER1_X_DRIVEN_SIM_VALUE 0
#define MONSTER1_X_EDGE_TYPE "NONE"
#define MONSTER1_X_FREQ 50000000
#define MONSTER1_X_HAS_IN 0
#define MONSTER1_X_HAS_OUT 1
#define MONSTER1_X_HAS_TRI 0
#define MONSTER1_X_IRQ -1
#define MONSTER1_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER1_X_IRQ_TYPE "NONE"
#define MONSTER1_X_NAME "/dev/monster1_x"
#define MONSTER1_X_RESET_VALUE 0
#define MONSTER1_X_SPAN 16
#define MONSTER1_X_TYPE "altera_avalon_pio"


/*
 * monster1_y configuration
 *
 */

#define ALT_MODULE_CLASS_monster1_y altera_avalon_pio
#define MONSTER1_Y_BASE 0x330
#define MONSTER1_Y_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER1_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER1_Y_CAPTURE 0
#define MONSTER1_Y_DATA_WIDTH 10
#define MONSTER1_Y_DO_TEST_BENCH_WIRING 0
#define MONSTER1_Y_DRIVEN_SIM_VALUE 0
#define MONSTER1_Y_EDGE_TYPE "NONE"
#define MONSTER1_Y_FREQ 50000000
#define MONSTER1_Y_HAS_IN 0
#define MONSTER1_Y_HAS_OUT 1
#define MONSTER1_Y_HAS_TRI 0
#define MONSTER1_Y_IRQ -1
#define MONSTER1_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER1_Y_IRQ_TYPE "NONE"
#define MONSTER1_Y_NAME "/dev/monster1_y"
#define MONSTER1_Y_RESET_VALUE 0
#define MONSTER1_Y_SPAN 16
#define MONSTER1_Y_TYPE "altera_avalon_pio"


/*
 * monster2_en configuration
 *
 */

#define ALT_MODULE_CLASS_monster2_en altera_avalon_pio
#define MONSTER2_EN_BASE 0x320
#define MONSTER2_EN_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER2_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER2_EN_CAPTURE 0
#define MONSTER2_EN_DATA_WIDTH 1
#define MONSTER2_EN_DO_TEST_BENCH_WIRING 0
#define MONSTER2_EN_DRIVEN_SIM_VALUE 0
#define MONSTER2_EN_EDGE_TYPE "NONE"
#define MONSTER2_EN_FREQ 50000000
#define MONSTER2_EN_HAS_IN 0
#define MONSTER2_EN_HAS_OUT 1
#define MONSTER2_EN_HAS_TRI 0
#define MONSTER2_EN_IRQ -1
#define MONSTER2_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER2_EN_IRQ_TYPE "NONE"
#define MONSTER2_EN_NAME "/dev/monster2_en"
#define MONSTER2_EN_RESET_VALUE 0
#define MONSTER2_EN_SPAN 16
#define MONSTER2_EN_TYPE "altera_avalon_pio"


/*
 * monster2_x configuration
 *
 */

#define ALT_MODULE_CLASS_monster2_x altera_avalon_pio
#define MONSTER2_X_BASE 0x310
#define MONSTER2_X_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER2_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER2_X_CAPTURE 0
#define MONSTER2_X_DATA_WIDTH 10
#define MONSTER2_X_DO_TEST_BENCH_WIRING 0
#define MONSTER2_X_DRIVEN_SIM_VALUE 0
#define MONSTER2_X_EDGE_TYPE "NONE"
#define MONSTER2_X_FREQ 50000000
#define MONSTER2_X_HAS_IN 0
#define MONSTER2_X_HAS_OUT 1
#define MONSTER2_X_HAS_TRI 0
#define MONSTER2_X_IRQ -1
#define MONSTER2_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER2_X_IRQ_TYPE "NONE"
#define MONSTER2_X_NAME "/dev/monster2_x"
#define MONSTER2_X_RESET_VALUE 0
#define MONSTER2_X_SPAN 16
#define MONSTER2_X_TYPE "altera_avalon_pio"


/*
 * monster2_y configuration
 *
 */

#define ALT_MODULE_CLASS_monster2_y altera_avalon_pio
#define MONSTER2_Y_BASE 0x300
#define MONSTER2_Y_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER2_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER2_Y_CAPTURE 0
#define MONSTER2_Y_DATA_WIDTH 10
#define MONSTER2_Y_DO_TEST_BENCH_WIRING 0
#define MONSTER2_Y_DRIVEN_SIM_VALUE 0
#define MONSTER2_Y_EDGE_TYPE "NONE"
#define MONSTER2_Y_FREQ 50000000
#define MONSTER2_Y_HAS_IN 0
#define MONSTER2_Y_HAS_OUT 1
#define MONSTER2_Y_HAS_TRI 0
#define MONSTER2_Y_IRQ -1
#define MONSTER2_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER2_Y_IRQ_TYPE "NONE"
#define MONSTER2_Y_NAME "/dev/monster2_y"
#define MONSTER2_Y_RESET_VALUE 0
#define MONSTER2_Y_SPAN 16
#define MONSTER2_Y_TYPE "altera_avalon_pio"


/*
 * monster3_dir configuration
 *
 */

#define ALT_MODULE_CLASS_monster3_dir altera_avalon_pio
#define MONSTER3_DIR_BASE 0x120
#define MONSTER3_DIR_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER3_DIR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER3_DIR_CAPTURE 0
#define MONSTER3_DIR_DATA_WIDTH 1
#define MONSTER3_DIR_DO_TEST_BENCH_WIRING 0
#define MONSTER3_DIR_DRIVEN_SIM_VALUE 0
#define MONSTER3_DIR_EDGE_TYPE "NONE"
#define MONSTER3_DIR_FREQ 50000000
#define MONSTER3_DIR_HAS_IN 0
#define MONSTER3_DIR_HAS_OUT 1
#define MONSTER3_DIR_HAS_TRI 0
#define MONSTER3_DIR_IRQ -1
#define MONSTER3_DIR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER3_DIR_IRQ_TYPE "NONE"
#define MONSTER3_DIR_NAME "/dev/monster3_dir"
#define MONSTER3_DIR_RESET_VALUE 0
#define MONSTER3_DIR_SPAN 16
#define MONSTER3_DIR_TYPE "altera_avalon_pio"


/*
 * monster3_en configuration
 *
 */

#define ALT_MODULE_CLASS_monster3_en altera_avalon_pio
#define MONSTER3_EN_BASE 0x2f0
#define MONSTER3_EN_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER3_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER3_EN_CAPTURE 0
#define MONSTER3_EN_DATA_WIDTH 1
#define MONSTER3_EN_DO_TEST_BENCH_WIRING 0
#define MONSTER3_EN_DRIVEN_SIM_VALUE 0
#define MONSTER3_EN_EDGE_TYPE "NONE"
#define MONSTER3_EN_FREQ 50000000
#define MONSTER3_EN_HAS_IN 0
#define MONSTER3_EN_HAS_OUT 1
#define MONSTER3_EN_HAS_TRI 0
#define MONSTER3_EN_IRQ -1
#define MONSTER3_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER3_EN_IRQ_TYPE "NONE"
#define MONSTER3_EN_NAME "/dev/monster3_en"
#define MONSTER3_EN_RESET_VALUE 0
#define MONSTER3_EN_SPAN 16
#define MONSTER3_EN_TYPE "altera_avalon_pio"


/*
 * monster3_x configuration
 *
 */

#define ALT_MODULE_CLASS_monster3_x altera_avalon_pio
#define MONSTER3_X_BASE 0x2e0
#define MONSTER3_X_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER3_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER3_X_CAPTURE 0
#define MONSTER3_X_DATA_WIDTH 10
#define MONSTER3_X_DO_TEST_BENCH_WIRING 0
#define MONSTER3_X_DRIVEN_SIM_VALUE 0
#define MONSTER3_X_EDGE_TYPE "NONE"
#define MONSTER3_X_FREQ 50000000
#define MONSTER3_X_HAS_IN 0
#define MONSTER3_X_HAS_OUT 1
#define MONSTER3_X_HAS_TRI 0
#define MONSTER3_X_IRQ -1
#define MONSTER3_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER3_X_IRQ_TYPE "NONE"
#define MONSTER3_X_NAME "/dev/monster3_x"
#define MONSTER3_X_RESET_VALUE 0
#define MONSTER3_X_SPAN 16
#define MONSTER3_X_TYPE "altera_avalon_pio"


/*
 * monster3_y configuration
 *
 */

#define ALT_MODULE_CLASS_monster3_y altera_avalon_pio
#define MONSTER3_Y_BASE 0x2d0
#define MONSTER3_Y_BIT_CLEARING_EDGE_REGISTER 0
#define MONSTER3_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MONSTER3_Y_CAPTURE 0
#define MONSTER3_Y_DATA_WIDTH 10
#define MONSTER3_Y_DO_TEST_BENCH_WIRING 0
#define MONSTER3_Y_DRIVEN_SIM_VALUE 0
#define MONSTER3_Y_EDGE_TYPE "NONE"
#define MONSTER3_Y_FREQ 50000000
#define MONSTER3_Y_HAS_IN 0
#define MONSTER3_Y_HAS_OUT 1
#define MONSTER3_Y_HAS_TRI 0
#define MONSTER3_Y_IRQ -1
#define MONSTER3_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MONSTER3_Y_IRQ_TYPE "NONE"
#define MONSTER3_Y_NAME "/dev/monster3_y"
#define MONSTER3_Y_RESET_VALUE 0
#define MONSTER3_Y_SPAN 16
#define MONSTER3_Y_TYPE "altera_avalon_pio"


/*
 * onchip_memory2_0 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_0 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "nios_system_onchip_memory2_0"
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_0_IRQ -1
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 16
#define ONCHIP_MEMORY2_0_SPAN 16
#define ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * otg_hpi_address configuration
 *
 */

#define ALT_MODULE_CLASS_otg_hpi_address altera_avalon_pio
#define OTG_HPI_ADDRESS_BASE 0x410
#define OTG_HPI_ADDRESS_BIT_CLEARING_EDGE_REGISTER 0
#define OTG_HPI_ADDRESS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OTG_HPI_ADDRESS_CAPTURE 0
#define OTG_HPI_ADDRESS_DATA_WIDTH 2
#define OTG_HPI_ADDRESS_DO_TEST_BENCH_WIRING 0
#define OTG_HPI_ADDRESS_DRIVEN_SIM_VALUE 0
#define OTG_HPI_ADDRESS_EDGE_TYPE "NONE"
#define OTG_HPI_ADDRESS_FREQ 50000000
#define OTG_HPI_ADDRESS_HAS_IN 0
#define OTG_HPI_ADDRESS_HAS_OUT 1
#define OTG_HPI_ADDRESS_HAS_TRI 0
#define OTG_HPI_ADDRESS_IRQ -1
#define OTG_HPI_ADDRESS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define OTG_HPI_ADDRESS_IRQ_TYPE "NONE"
#define OTG_HPI_ADDRESS_NAME "/dev/otg_hpi_address"
#define OTG_HPI_ADDRESS_RESET_VALUE 0
#define OTG_HPI_ADDRESS_SPAN 16
#define OTG_HPI_ADDRESS_TYPE "altera_avalon_pio"


/*
 * otg_hpi_cs configuration
 *
 */

#define ALT_MODULE_CLASS_otg_hpi_cs altera_avalon_pio
#define OTG_HPI_CS_BASE 0x3d0
#define OTG_HPI_CS_BIT_CLEARING_EDGE_REGISTER 0
#define OTG_HPI_CS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OTG_HPI_CS_CAPTURE 0
#define OTG_HPI_CS_DATA_WIDTH 1
#define OTG_HPI_CS_DO_TEST_BENCH_WIRING 0
#define OTG_HPI_CS_DRIVEN_SIM_VALUE 0
#define OTG_HPI_CS_EDGE_TYPE "NONE"
#define OTG_HPI_CS_FREQ 50000000
#define OTG_HPI_CS_HAS_IN 0
#define OTG_HPI_CS_HAS_OUT 1
#define OTG_HPI_CS_HAS_TRI 0
#define OTG_HPI_CS_IRQ -1
#define OTG_HPI_CS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define OTG_HPI_CS_IRQ_TYPE "NONE"
#define OTG_HPI_CS_NAME "/dev/otg_hpi_cs"
#define OTG_HPI_CS_RESET_VALUE 0
#define OTG_HPI_CS_SPAN 16
#define OTG_HPI_CS_TYPE "altera_avalon_pio"


/*
 * otg_hpi_data configuration
 *
 */

#define ALT_MODULE_CLASS_otg_hpi_data altera_avalon_pio
#define OTG_HPI_DATA_BASE 0x400
#define OTG_HPI_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define OTG_HPI_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OTG_HPI_DATA_CAPTURE 0
#define OTG_HPI_DATA_DATA_WIDTH 16
#define OTG_HPI_DATA_DO_TEST_BENCH_WIRING 0
#define OTG_HPI_DATA_DRIVEN_SIM_VALUE 0
#define OTG_HPI_DATA_EDGE_TYPE "NONE"
#define OTG_HPI_DATA_FREQ 50000000
#define OTG_HPI_DATA_HAS_IN 1
#define OTG_HPI_DATA_HAS_OUT 1
#define OTG_HPI_DATA_HAS_TRI 0
#define OTG_HPI_DATA_IRQ -1
#define OTG_HPI_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define OTG_HPI_DATA_IRQ_TYPE "NONE"
#define OTG_HPI_DATA_NAME "/dev/otg_hpi_data"
#define OTG_HPI_DATA_RESET_VALUE 0
#define OTG_HPI_DATA_SPAN 16
#define OTG_HPI_DATA_TYPE "altera_avalon_pio"


/*
 * otg_hpi_r configuration
 *
 */

#define ALT_MODULE_CLASS_otg_hpi_r altera_avalon_pio
#define OTG_HPI_R_BASE 0x3f0
#define OTG_HPI_R_BIT_CLEARING_EDGE_REGISTER 0
#define OTG_HPI_R_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OTG_HPI_R_CAPTURE 0
#define OTG_HPI_R_DATA_WIDTH 1
#define OTG_HPI_R_DO_TEST_BENCH_WIRING 0
#define OTG_HPI_R_DRIVEN_SIM_VALUE 0
#define OTG_HPI_R_EDGE_TYPE "NONE"
#define OTG_HPI_R_FREQ 50000000
#define OTG_HPI_R_HAS_IN 0
#define OTG_HPI_R_HAS_OUT 1
#define OTG_HPI_R_HAS_TRI 0
#define OTG_HPI_R_IRQ -1
#define OTG_HPI_R_IRQ_INTERRUPT_CONTROLLER_ID -1
#define OTG_HPI_R_IRQ_TYPE "NONE"
#define OTG_HPI_R_NAME "/dev/otg_hpi_r"
#define OTG_HPI_R_RESET_VALUE 0
#define OTG_HPI_R_SPAN 16
#define OTG_HPI_R_TYPE "altera_avalon_pio"


/*
 * otg_hpi_w configuration
 *
 */

#define ALT_MODULE_CLASS_otg_hpi_w altera_avalon_pio
#define OTG_HPI_W_BASE 0x3e0
#define OTG_HPI_W_BIT_CLEARING_EDGE_REGISTER 0
#define OTG_HPI_W_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OTG_HPI_W_CAPTURE 0
#define OTG_HPI_W_DATA_WIDTH 1
#define OTG_HPI_W_DO_TEST_BENCH_WIRING 0
#define OTG_HPI_W_DRIVEN_SIM_VALUE 0
#define OTG_HPI_W_EDGE_TYPE "NONE"
#define OTG_HPI_W_FREQ 50000000
#define OTG_HPI_W_HAS_IN 0
#define OTG_HPI_W_HAS_OUT 1
#define OTG_HPI_W_HAS_TRI 0
#define OTG_HPI_W_IRQ -1
#define OTG_HPI_W_IRQ_INTERRUPT_CONTROLLER_ID -1
#define OTG_HPI_W_IRQ_TYPE "NONE"
#define OTG_HPI_W_NAME "/dev/otg_hpi_w"
#define OTG_HPI_W_RESET_VALUE 0
#define OTG_HPI_W_SPAN 16
#define OTG_HPI_W_TYPE "altera_avalon_pio"


/*
 * samus_dir configuration
 *
 */

#define ALT_MODULE_CLASS_samus_dir altera_avalon_pio
#define SAMUS_DIR_BASE 0x160
#define SAMUS_DIR_BIT_CLEARING_EDGE_REGISTER 0
#define SAMUS_DIR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SAMUS_DIR_CAPTURE 0
#define SAMUS_DIR_DATA_WIDTH 1
#define SAMUS_DIR_DO_TEST_BENCH_WIRING 0
#define SAMUS_DIR_DRIVEN_SIM_VALUE 0
#define SAMUS_DIR_EDGE_TYPE "NONE"
#define SAMUS_DIR_FREQ 50000000
#define SAMUS_DIR_HAS_IN 0
#define SAMUS_DIR_HAS_OUT 1
#define SAMUS_DIR_HAS_TRI 0
#define SAMUS_DIR_IRQ -1
#define SAMUS_DIR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SAMUS_DIR_IRQ_TYPE "NONE"
#define SAMUS_DIR_NAME "/dev/samus_dir"
#define SAMUS_DIR_RESET_VALUE 0
#define SAMUS_DIR_SPAN 16
#define SAMUS_DIR_TYPE "altera_avalon_pio"


/*
 * samus_en configuration
 *
 */

#define ALT_MODULE_CLASS_samus_en altera_avalon_pio
#define SAMUS_EN_BASE 0x3a0
#define SAMUS_EN_BIT_CLEARING_EDGE_REGISTER 0
#define SAMUS_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SAMUS_EN_CAPTURE 0
#define SAMUS_EN_DATA_WIDTH 1
#define SAMUS_EN_DO_TEST_BENCH_WIRING 0
#define SAMUS_EN_DRIVEN_SIM_VALUE 0
#define SAMUS_EN_EDGE_TYPE "NONE"
#define SAMUS_EN_FREQ 50000000
#define SAMUS_EN_HAS_IN 0
#define SAMUS_EN_HAS_OUT 1
#define SAMUS_EN_HAS_TRI 0
#define SAMUS_EN_IRQ -1
#define SAMUS_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SAMUS_EN_IRQ_TYPE "NONE"
#define SAMUS_EN_NAME "/dev/samus_en"
#define SAMUS_EN_RESET_VALUE 0
#define SAMUS_EN_SPAN 16
#define SAMUS_EN_TYPE "altera_avalon_pio"


/*
 * samus_jump configuration
 *
 */

#define ALT_MODULE_CLASS_samus_jump altera_avalon_pio
#define SAMUS_JUMP_BASE 0x360
#define SAMUS_JUMP_BIT_CLEARING_EDGE_REGISTER 0
#define SAMUS_JUMP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SAMUS_JUMP_CAPTURE 0
#define SAMUS_JUMP_DATA_WIDTH 1
#define SAMUS_JUMP_DO_TEST_BENCH_WIRING 0
#define SAMUS_JUMP_DRIVEN_SIM_VALUE 0
#define SAMUS_JUMP_EDGE_TYPE "NONE"
#define SAMUS_JUMP_FREQ 50000000
#define SAMUS_JUMP_HAS_IN 0
#define SAMUS_JUMP_HAS_OUT 1
#define SAMUS_JUMP_HAS_TRI 0
#define SAMUS_JUMP_IRQ -1
#define SAMUS_JUMP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SAMUS_JUMP_IRQ_TYPE "NONE"
#define SAMUS_JUMP_NAME "/dev/samus_jump"
#define SAMUS_JUMP_RESET_VALUE 0
#define SAMUS_JUMP_SPAN 16
#define SAMUS_JUMP_TYPE "altera_avalon_pio"


/*
 * samus_up configuration
 *
 */

#define ALT_MODULE_CLASS_samus_up altera_avalon_pio
#define SAMUS_UP_BASE 0x140
#define SAMUS_UP_BIT_CLEARING_EDGE_REGISTER 0
#define SAMUS_UP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SAMUS_UP_CAPTURE 0
#define SAMUS_UP_DATA_WIDTH 1
#define SAMUS_UP_DO_TEST_BENCH_WIRING 0
#define SAMUS_UP_DRIVEN_SIM_VALUE 0
#define SAMUS_UP_EDGE_TYPE "NONE"
#define SAMUS_UP_FREQ 50000000
#define SAMUS_UP_HAS_IN 0
#define SAMUS_UP_HAS_OUT 1
#define SAMUS_UP_HAS_TRI 0
#define SAMUS_UP_IRQ -1
#define SAMUS_UP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SAMUS_UP_IRQ_TYPE "NONE"
#define SAMUS_UP_NAME "/dev/samus_up"
#define SAMUS_UP_RESET_VALUE 0
#define SAMUS_UP_SPAN 16
#define SAMUS_UP_TYPE "altera_avalon_pio"


/*
 * samus_walk configuration
 *
 */

#define ALT_MODULE_CLASS_samus_walk altera_avalon_pio
#define SAMUS_WALK_BASE 0x370
#define SAMUS_WALK_BIT_CLEARING_EDGE_REGISTER 0
#define SAMUS_WALK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SAMUS_WALK_CAPTURE 0
#define SAMUS_WALK_DATA_WIDTH 1
#define SAMUS_WALK_DO_TEST_BENCH_WIRING 0
#define SAMUS_WALK_DRIVEN_SIM_VALUE 0
#define SAMUS_WALK_EDGE_TYPE "NONE"
#define SAMUS_WALK_FREQ 50000000
#define SAMUS_WALK_HAS_IN 0
#define SAMUS_WALK_HAS_OUT 1
#define SAMUS_WALK_HAS_TRI 0
#define SAMUS_WALK_IRQ -1
#define SAMUS_WALK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SAMUS_WALK_IRQ_TYPE "NONE"
#define SAMUS_WALK_NAME "/dev/samus_walk"
#define SAMUS_WALK_RESET_VALUE 0
#define SAMUS_WALK_SPAN 16
#define SAMUS_WALK_TYPE "altera_avalon_pio"


/*
 * samus_x configuration
 *
 */

#define ALT_MODULE_CLASS_samus_x altera_avalon_pio
#define SAMUS_X_BASE 0x390
#define SAMUS_X_BIT_CLEARING_EDGE_REGISTER 0
#define SAMUS_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SAMUS_X_CAPTURE 0
#define SAMUS_X_DATA_WIDTH 10
#define SAMUS_X_DO_TEST_BENCH_WIRING 0
#define SAMUS_X_DRIVEN_SIM_VALUE 0
#define SAMUS_X_EDGE_TYPE "NONE"
#define SAMUS_X_FREQ 50000000
#define SAMUS_X_HAS_IN 0
#define SAMUS_X_HAS_OUT 1
#define SAMUS_X_HAS_TRI 0
#define SAMUS_X_IRQ -1
#define SAMUS_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SAMUS_X_IRQ_TYPE "NONE"
#define SAMUS_X_NAME "/dev/samus_x"
#define SAMUS_X_RESET_VALUE 0
#define SAMUS_X_SPAN 16
#define SAMUS_X_TYPE "altera_avalon_pio"


/*
 * samus_y configuration
 *
 */

#define ALT_MODULE_CLASS_samus_y altera_avalon_pio
#define SAMUS_Y_BASE 0x380
#define SAMUS_Y_BIT_CLEARING_EDGE_REGISTER 0
#define SAMUS_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SAMUS_Y_CAPTURE 0
#define SAMUS_Y_DATA_WIDTH 10
#define SAMUS_Y_DO_TEST_BENCH_WIRING 0
#define SAMUS_Y_DRIVEN_SIM_VALUE 0
#define SAMUS_Y_EDGE_TYPE "NONE"
#define SAMUS_Y_FREQ 50000000
#define SAMUS_Y_HAS_IN 0
#define SAMUS_Y_HAS_OUT 1
#define SAMUS_Y_HAS_TRI 0
#define SAMUS_Y_IRQ -1
#define SAMUS_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SAMUS_Y_IRQ_TYPE "NONE"
#define SAMUS_Y_NAME "/dev/samus_y"
#define SAMUS_Y_RESET_VALUE 0
#define SAMUS_Y_SPAN 16
#define SAMUS_Y_TYPE "altera_avalon_pio"


/*
 * scene_sel configuration
 *
 */

#define ALT_MODULE_CLASS_scene_sel altera_avalon_pio
#define SCENE_SEL_BASE 0x150
#define SCENE_SEL_BIT_CLEARING_EDGE_REGISTER 0
#define SCENE_SEL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SCENE_SEL_CAPTURE 0
#define SCENE_SEL_DATA_WIDTH 3
#define SCENE_SEL_DO_TEST_BENCH_WIRING 0
#define SCENE_SEL_DRIVEN_SIM_VALUE 0
#define SCENE_SEL_EDGE_TYPE "NONE"
#define SCENE_SEL_FREQ 50000000
#define SCENE_SEL_HAS_IN 0
#define SCENE_SEL_HAS_OUT 1
#define SCENE_SEL_HAS_TRI 0
#define SCENE_SEL_IRQ -1
#define SCENE_SEL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SCENE_SEL_IRQ_TYPE "NONE"
#define SCENE_SEL_NAME "/dev/scene_sel"
#define SCENE_SEL_RESET_VALUE 0
#define SCENE_SEL_SPAN 16
#define SCENE_SEL_TYPE "altera_avalon_pio"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x10000000
#define SDRAM_CAS_LATENCY 3
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 2
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_POWERUP_DELAY 200.0
#define SDRAM_REFRESH_PERIOD 7.8125
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 10
#define SDRAM_SDRAM_DATA_WIDTH 32
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 13
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 0
#define SDRAM_SPAN 134217728
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.5
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 20.0
#define SDRAM_T_RFC 70.0
#define SDRAM_T_RP 20.0
#define SDRAM_T_WR 14.0


/*
 * sdram_pll configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_pll altpll
#define SDRAM_PLL_BASE 0x420
#define SDRAM_PLL_IRQ -1
#define SDRAM_PLL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_PLL_NAME "/dev/sdram_pll"
#define SDRAM_PLL_SPAN 16
#define SDRAM_PLL_TYPE "altpll"


/*
 * sysid_qsys_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys_0 altera_avalon_sysid_qsys
#define SYSID_QSYS_0_BASE 0x438
#define SYSID_QSYS_0_ID 0
#define SYSID_QSYS_0_IRQ -1
#define SYSID_QSYS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_0_NAME "/dev/sysid_qsys_0"
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_TIMESTAMP 1480905656
#define SYSID_QSYS_0_TYPE "altera_avalon_sysid_qsys"


/*
 * title_en configuration
 *
 */

#define ALT_MODULE_CLASS_title_en altera_avalon_pio
#define TITLE_EN_BASE 0x190
#define TITLE_EN_BIT_CLEARING_EDGE_REGISTER 0
#define TITLE_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TITLE_EN_CAPTURE 0
#define TITLE_EN_DATA_WIDTH 1
#define TITLE_EN_DO_TEST_BENCH_WIRING 0
#define TITLE_EN_DRIVEN_SIM_VALUE 0
#define TITLE_EN_EDGE_TYPE "NONE"
#define TITLE_EN_FREQ 50000000
#define TITLE_EN_HAS_IN 0
#define TITLE_EN_HAS_OUT 1
#define TITLE_EN_HAS_TRI 0
#define TITLE_EN_IRQ -1
#define TITLE_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TITLE_EN_IRQ_TYPE "NONE"
#define TITLE_EN_NAME "/dev/title_en"
#define TITLE_EN_RESET_VALUE 0
#define TITLE_EN_SPAN 16
#define TITLE_EN_TYPE "altera_avalon_pio"


/*
 * win_en configuration
 *
 */

#define ALT_MODULE_CLASS_win_en altera_avalon_pio
#define WIN_EN_BASE 0x170
#define WIN_EN_BIT_CLEARING_EDGE_REGISTER 0
#define WIN_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define WIN_EN_CAPTURE 0
#define WIN_EN_DATA_WIDTH 1
#define WIN_EN_DO_TEST_BENCH_WIRING 0
#define WIN_EN_DRIVEN_SIM_VALUE 0
#define WIN_EN_EDGE_TYPE "NONE"
#define WIN_EN_FREQ 50000000
#define WIN_EN_HAS_IN 0
#define WIN_EN_HAS_OUT 1
#define WIN_EN_HAS_TRI 0
#define WIN_EN_IRQ -1
#define WIN_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define WIN_EN_IRQ_TYPE "NONE"
#define WIN_EN_NAME "/dev/win_en"
#define WIN_EN_RESET_VALUE 0
#define WIN_EN_SPAN 16
#define WIN_EN_TYPE "altera_avalon_pio"

#endif /* __SYSTEM_H_ */
